### ISSUE TITLE
Outdated docs on SystemGraph::root

### ISSUE THREAD

**Issue by alice-i-cecile** [HouraiTeahouse/bevy_system_graph#3]
> Creates a new [SystemGraph](https://docs.rs/bevy_system_graph/0.1.1/bevy_system_graph/struct.SystemGraph.html) with specific graph ID. Should be exclusively for testing purposes. Creates a root graph node without any dependencies. A graph can have multiple distinct root nodes.

However, this method is prominently used in the examples.

I also don't see any way to pass in a specific graph id

**Comment by james7132** [comment]
This package is now deprecated in favor of Bevy's ECS Schedule V3 introduced in 0.10.
