### ISSUE TITLE
SystemGraph::root does not take a `&mut self`

### ISSUE THREAD

**Issue by alice-i-cecile** [HouraiTeahouse/bevy_system_graph#4]
This was surprising to me, and is suspicious, given that we appear to be mutating the underlying SystemGraph.

**Comment by james7132** [comment]
The entire graph utilizes interior mutability as a base. You can also see that conversion into a `SystemSet` drains the graph entirely, but leaves existing nodes around. Didn't give the thought of what users could do with the graph after it's been converted . I'll look into another ergonomic option that doesn't allow this.

**Comment by james7132** [comment]
This package is now deprecated in favor of Bevy's ECS Schedule V3 introduced in 0.10.
