### ISSUE TITLE
Implement SystemJoin for tuples of references

### ISSUE THREAD

**Issue by farnoy** [HouraiTeahouse/bevy_system_graph#5]
I find that using `join()` and `join_all()` is less ergonomic than it could, due to the copying required to use these.

```rs
let a = graph.root(...);
let b = graph.root(...);
let c = graph.root(...);

let ab = (a, b.clone()).join(...);
//            ^^^^^^^^
let bc = (b, c).join(...);
```

**Comment by james7132** [comment]
Unfortunately, implementing `SystemJoin` and friends for references to nodes still requires a `(a, &b)` kind of structure. which is still a bit rough on the eyes.

One solution could be to make the type `Copy`, though I'm not too happy about that potential outcome and the implications that come with copy-default semantic, and the copying is indeed non-trivial. Though the usefulness of the graph is really only limited to App setup right now, so ergonomics here might be a priority over potential heavy misuse: we can always just say "that's a bad idea, don't do that".

**Comment by james7132** [comment]
This package is now deprecated in favor of Bevy's ECS Schedule V3 introduced in 0.10.
